properties:
  resources:
    ## Windows Settings ##
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Modify taskbar settings
        allowPrerelease: true
      settings:
        Alignment: Middle
        HideLabelsMode: Never
        SearchBoxMode: Hide
        TaskViewButton: Show
        WidgetsButton: Hide
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for `HideLabelsMode`.
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Modify Windows Explorer settings
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
        ItemCheckBoxes: Show
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for all WindowsExplorer settings.
    
    ## Terminal ##        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget

    ## Command line tools ##
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Ripgrep for Windows
        allowPrerelease: true
      settings:
        id:  BurntSushi.ripgrep.MSVC
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id:  Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Powershell 7
        allowPrerelease: true
      settings:
        id:  Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
        id:  Microsoft.AzureCLI
        source: winget     

    ## Development
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id:  Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id:  Docker.DockerDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Python
        allowPrerelease: true
      settings:
        id:  Python.Python.3.12
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install SQL Server Management Studio
        allowPrerelease: true
      settings:
        id:  Microsoft.SQLServerManagementStudio
        source: winget

    ## Styling ##
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Oh-My-Posh
        allowPrerelease: true
      settings:
        id:  JanDeDobbeleer.OhMyPosh
        source: winget

    ## Apps ##
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id:  Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Teams
        allowPrerelease: true
      settings:
        id:  Microsoft.Teams
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Spotify
        allowPrerelease: true
      settings:
        id:  Spotify.Spotify
        source: winget

    ## Repos ##
    # - resource: GitDsc/GitClone
    #   directives:
    #     description: Clone a repository
    #     allowPrerelease: true
    #   settings:
    #     HttpsUrl: https://github.com/microsoft/winget-cli.git
    #     RootDirectory: '${WingetConfigRoot}/'
   
  configurationVersion: 0.2.0